image:
  repository: ghcr.io/schedule-rsreu/schedule3
  tag: ""
  pullPolicy: IfNotPresent

replicas: 1

resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 200m
    memory: 64Mi

ingress:
  enabled: true
  hosts:
    - schedule.vingp.dev
    - rsreu-schedule.ru
